repos:
- repo: local
  hooks:
  -   id: yapf
      name: yapf
      entry: yapf
      language: python
      'types': [python]
      args: ["-i"]
      require_serial: false
      additional_dependencies: [toml]
      minimum_pre_commit_version: '0'
