[tool.poetry]
name = "gitignore-template"
version = "0.0.0"
description = "Downloads a gitignore template from https://github.com/github/gitignore for your project"
authors = ["Jonathan Boyle <programmerfalcon@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
